name: Build and publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
      - name: Install dependencies
        run: dotnet restore ./Portfolio/Portfolio.csproj
      - name: Publish csproj
        run: dotnet publish ./Portfolio/Portfolio.csproj -c:Release -p:GHPages=true -o out/Portfolio --nologo --no-restore
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: build
          FOLDER: out/Portfolio/wwwroot
